// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4AiUzCgl-z6_QIoN_ZM-3pO4CCkJiSs',
    appId: '1:262926188813:web:7ec9d28470b7b2360ab044',
    messagingSenderId: '262926188813',
    projectId: 'chat-app-20117',
    authDomain: 'chat-app-20117.firebaseapp.com',
    storageBucket: 'chat-app-20117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbCNqoxcUko5hGM0Ss9AyN86n-W46yU80',
    appId: '1:262926188813:android:840cd3bd354a95190ab044',
    messagingSenderId: '262926188813',
    projectId: 'chat-app-20117',
    storageBucket: 'chat-app-20117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Tlue7A3y5_RrLHbpT17Vmia9ileUWgE',
    appId: '1:262926188813:ios:1a927ccd8013e3ac0ab044',
    messagingSenderId: '262926188813',
    projectId: 'chat-app-20117',
    storageBucket: 'chat-app-20117.appspot.com',
    iosBundleId: 'com.example.flutterPosEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Tlue7A3y5_RrLHbpT17Vmia9ileUWgE',
    appId: '1:262926188813:ios:1a927ccd8013e3ac0ab044',
    messagingSenderId: '262926188813',
    projectId: 'chat-app-20117',
    storageBucket: 'chat-app-20117.appspot.com',
    iosBundleId: 'com.example.flutterPosEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4AiUzCgl-z6_QIoN_ZM-3pO4CCkJiSs',
    appId: '1:262926188813:web:e4c1abc6a4507a380ab044',
    messagingSenderId: '262926188813',
    projectId: 'chat-app-20117',
    authDomain: 'chat-app-20117.firebaseapp.com',
    storageBucket: 'chat-app-20117.appspot.com',
  );
}
